vim.api.nvim_set_hl(0, "Normal", { bg = "none" })
vim.api.nvim_set_hl(0, "NormalFloat", { bg = "#171719" })
vim.api.nvim_set_hl(0, "FloatBorder", { bg = "#171719" })
vim.api.nvim_set_hl(0, "LineNr", { bg = "none", fg = "#524b5f" })
-- vim.api.nvim_set_hl(0, "CursorLineNr", { bg = "none", fg = "white" })
vim.api.nvim_set_hl(0, "SignColumn", { bg = "none" })
vim.api.nvim_set_hl(0, "NonText", { bg = "none" })
vim.api.nvim_set_hl(0, "EndOfBuffer", { bg = "none" })
vim.api.nvim_set_hl(0, "TabLineFill", { bg = "none" })

vim.api.nvim_set_hl(0, "TreesitterContext", { bg = "none", bold = true, italic = true })
vim.api.nvim_set_hl(0, "TreesitterContextLineNumber", { fg = "#a9b1d6", bold = true })
-- vim.api.nvim_set_hl(0, "TreesitterContextSeparator", { fg = "#555568", bg = "none" })
-- vim.api.nvim_set_hl(0, "TreesitterContextBottom", { underline = true })
